import type { Metadata } from "next";
import "./globals.css";
import AppNav from "@/components/navitation/AppNav";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" style={{ filter: "invert(0)" }} className="">
      <body>
        <SessionProvider>
          <main className="max-w-[1280px] mx-auto">
            <section>
              <AppNav />
            </section>
            <section>
              {children}
              <Toaster position="top-right" richColors closeButton />
            </section>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";
// import AppNav from "@/components/navitation/AppNav";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Snap Shop",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" style={{ filter: "invert(0)" }} className="">
//       <body className={`${geistSans.variable} ${geistMono.variable} `}>
//         <div className="antialiased max-w-7xl mx-auto px-6 lg:px-8">
//           <AppNav />

//           <section>
//             {children}
//             <Toaster position="top-center" richColors closeButton />
//           </section>
//         </div>
//       </body>
//     </html>
//   );
// }
